### ISSUE TITLE
http://dev.cryptolions.io/  sendCoins show "temporary closed"

### ISSUE THREAD

**Issue by clumsyroger** [Hashbit-Technologies/eoswalletpro#1]
Hey,bro.I clicked sendCoins by the tutorial,but the dev.cryptolions shows "temporary closed",Is there another way to test?

**Comment by ghost** [comment]
The BP's on the Jungle testnet closed the account faucet and stopped all transactions to try and solve a ```cpu limit``` bug. Not sure when it will be back on. You can ask in here https://t.me/jungletestnet
